version: '3'
services:

    storage54.front.admin:
        build: ./front/admin
        volumes:
            - ./front/admin/src:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - storage54
        environment:
            - NAME=front.admin
        env_file:
            - .env

    storage54.front.public:
        build: ./front/public
        volumes:
            - ./front/public/src:/usr/src/app
        command: sh -c " npm install && npm start "
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - storage54
        environment:
            - NAME=front.public
        env_file:
            - .env

    # База данных
    storage54.db.postgresql:
        build:
            context: ./servers/postgresql
            dockerfile: Dockerfile
        volumes:
            - ./volumes/db/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            - NAME=storage54.db.postgresql
        env_file:
            -   ./.env
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - storage54



    # Redis сервер для обработки очередей
    storage54.db.redis:
        build:
            context: ./servers/redis
            dockerfile: Dockerfile
        volumes:
            - ./volumes/redis:/data
        ports:
            - "6379:6379"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - storage54


    # Роутер на основе nginx
    # Он принимает запросы и передает их соответствующему сервису
    storage54.nginx:
        build:
            context: ./servers/nginx
            dockerfile: Dockerfile
        volumes:
            - ./servers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./volumes/nginx/log:/var/log/nginx
        ports:
            - "80:80"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - storage54


networks:
    storage54:
        driver: bridge
