# Устанавливаем базовый образ PHP
FROM php:8.3-cli

# Установка утилиты unzip
RUN apt update && apt install -y unzip mc

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Установка дополнительных расширений PHP для Redis
RUN pecl install redis && docker-php-ext-enable redis

# Установка библиотеки ImageMagick и её заголовочных файлов
RUN apt-get install -y libmagickwand-dev
# Установка расширения Imagick
RUN pecl install imagick && docker-php-ext-enable imagick

# Установка PostgreSQL клиента и расширения PDO для PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client libpq-dev

# Устанавливаем необходимые расширения PHP, включая pdo_pgsql
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql

# Устанавливаем рабочую директорию
WORKDIR /var/www/html
# Копирование и установка зависимостей PHP
COPY src /var/www/html
RUN composer install

# Установка supervisord
RUN apt-get install -y supervisor
# Копирование конфигурационного файла supervisord для воркеров очереди
COPY supervisor_job.conf /etc/supervisor/conf.d/supervisord.conf
# Запуск сервисов контейнера
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
